// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_callback from "./routes/api/auth/callback.ts";
import * as $api_auth_google from "./routes/api/auth/google.ts";
import * as $api_exams_id_delete from "./routes/api/exams/[id]/delete.ts";
import * as $api_exams_create from "./routes/api/exams/create.ts";
import * as $api_tasks_id_toggle from "./routes/api/tasks/[id]/toggle.ts";
import * as $exams_id_ from "./routes/exams/[id].tsx";
import * as $exams_new from "./routes/exams/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $TaskCheckbox from "./islands/TaskCheckbox.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/callback.ts": $api_auth_callback,
    "./routes/api/auth/google.ts": $api_auth_google,
    "./routes/api/exams/[id]/delete.ts": $api_exams_id_delete,
    "./routes/api/exams/create.ts": $api_exams_create,
    "./routes/api/tasks/[id]/toggle.ts": $api_tasks_id_toggle,
    "./routes/exams/[id].tsx": $exams_id_,
    "./routes/exams/new.tsx": $exams_new,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/TaskCheckbox.tsx": $TaskCheckbox,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
