// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_mock from "./routes/api/auth/mock.ts";
import * as $api_exams_create from "./routes/api/exams/create.ts";
import * as $exams_new from "./routes/exams/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/mock.ts": $api_auth_mock,
    "./routes/api/exams/create.ts": $api_exams_create,
    "./routes/exams/new.tsx": $exams_new,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
